---
name: Deploy to Ansible Galaxy
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-latest
    #if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            docker
            flake8
      - run: ./test.sh
